apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghee-app
  labels:
    first: app
spec: #defines the behavior of the replicaset
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: #defines the behavior of the pod
      containers:
        - name: my-ghee
          image: 16akash/organic:v1.0.0
          ports:
            - containerPort: 5656
          envFrom:
            - configMapRef:
                name: akash-configmap
            - secretRef:
                name: akash-secrete
 
---
apiVersion: v1
kind: Service
metadata:
  name: ghee-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 5656
      targetPort: 5656
 
  type: NodePort